version: '3.4'
services:
  app:
    image: python-flask-base:1.0.0
    container_name: python-flask-base
    ports:
      - 8000:8000

  db:
    image: postgres
    restart: always
    container_name: db
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080