swagger: "2.0"
info:
  description: "QIM - API"
  version: "1"
  title: "Swagger QIM"
schemes:
  - "https"
  - "http"
paths:
  /conta/{conta}/almoxarifado:
    options:
      x-swagger-router-controller: controller.common
      operationId: options
      produces:
        - "application/json"
      parameters:
        - in: "path"
          name: "conta"
          required: true
          type: "string"
      summary: CORS support
      description: Enable CORS by returning correct headers
      responses:
        200:
          description: Default response for CORS method
    get:
      x-swagger-router-controller: controller.almoxarifado
      operationId: search
      produces:
        - "application/json"
      parameters:
        - in: "path"
          name: "conta"
          required: true
          type: "string"
      responses:
        "200":
          description: "Ok"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/almoxarifado"
        "401":
          description: "Unauthorized"

definitions:
  almoxarifado:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      nome:
        type: "string"
      descricao:
        type: "string"